### PR TITLE
Add setup.py file to project

### LINKED ISSUE #40: package up for PyPI
```
What steps will reproduce the problem?
1.pip search fabricate

What is the expected output? What do you see instead?

  I expect to see fabricate listed :)  Instead... I don't.

What version of the product are you using? On what operating system?

  Any version up to May 3rd, 2013

Please provide any additional information below.

  IWBNI projects that I work on could set up fabricate as a build-depends much like other python test tools and etc.

```

Original issue reported on code.google.com by `pjimen...@gmail.com` on 27 May 2013 at 2:13

### PR DESCRIPTION
**Pull request by chriscz**
Took the setup.py file from the `pypi` package and add it here. Closes #40. Should contact @JDeuce to transfer ownership as soon as this has been merged.

### CODE REVIEW

**Comment by JDeuce** [comment]
Yeah I'll transfer it, just let me know what your PyPI username is.

**Comment by rmatev** [comment]
Is this repo alive? Nothing has been merged since it moved to github

**Comment by SimonAlfie** [comment]
To be honest, not really. I have not managed to make time to maintain it.

**Comment by rmatev** [comment]
In that case wouldn't it make sense to add more writers? It's not very healthy for the project to have this many forks, which never converge.

**Comment by chriscz** [comment]
@SimonAlfie , 
I'm willing to help out merging some of the pull-requests and responding to issues in my spare time.

**Comment by SimonAlfie** [comment]
Sure, I will add more writers. I will start with you Chris. Should I add
you also Rosen?

Simon.

**Comment by rmatev** [comment]
Yes, I'll be happy to help out!

**Comment by SimonAlfie** [comment]
You now both have access push access. I trust you know what your doing :) .
I am guilty of letting the project go stale, so glad people are still
interested enough in it to help out.

Simon.

**Comment by chriscz** [comment]
Thanks Simon!
I'm actively using fabricate as an alternative to make for my some of my projects.
@JDeuce, could you please transfer ownership to to `chriscz`.

**Comment by JDeuce** [comment]
@chriscz  check your PyPI account

**Comment by chriscz** [comment]
Thanks @JDeuce I now have access.

**Pull request merged**
