### PR TITLE
Corrected function parameter arg->args[0]

### PR DESCRIPTION
**Pull request by edin1**

### CODE REVIEW

**Comment by SimonAlfie** [comment]
Can you explain what the effect the bug was having on fabricate?

**Comment by edin1** [comment]
Did you look at the code? It's difficult to understand the fix without looking at the code. The line is inside of the function `run(*args, **kwargs)`, and the docstring for that function says *"...If there is only one positional argument which is an iterable treat each element as a command...".*

In the old code, the `arg` variable is used, but it's not defined prior to that usage (which is a bug). However, because it is inside of the right part  of a boolean `and` operation, the right part (containing the bug) of the operation is rarely invoked (only when a user calls `run` with e.g. `run(['command', 'arg'])`) because of short-circuitring (`and` is a short-circuit operator in Python), so the bug is rarely invoked.

There are some other problems with the behaviour of `run`, but that's another story...

**Comment by pjz** [comment]
:+1:

**Comment by chriscz** [comment]
Fixed by merging of #67

**Pull request closed without merging**
