### PR TITLE
Python3 compatibility

### LINKED ISSUE #38: Python3 support
```
What steps will reproduce the problem?
1. attempt to import or run fabricate with python 3+

I wasn't necessarily expecting Python3 (python 3, py3k, whatever) to be 
supported, but am working on making a codebase that *uses* fabricate 
Python3-compatible.

I'm using fabricate 1.25 on both OSX and Linux with Python 3.3.0.

Attached is a patch that works for my uses but is probably not exhaustive.
```

Original issue reported on code.google.com by `daniel.b...@gmail.com` on 7 Apr 2013 at 1:39

Attachments:
* [fabricate-py3k-r163.patch](https://storage.googleapis.com/google-code-attachments/fabricate/issue-38/comment-0/fabricate-py3k-r163.patch)

### PR DESCRIPTION
**Pull request by Changaco**
Closes #38.

### CODE REVIEW

**Comment by pjz** [comment]
+1 - we're using this at in http://aspen.io/ now.

**Comment by SimonAlfie** [comment]
OK. I Will take a look at pulling this and merging to master in the
fabricate repository.

**Comment by Changaco** [comment]
You mean doing it manually instead of letting GitHub do it for you?

**Comment by SimonAlfie** [comment]
No, I mean using Git Hub to do it. Never done it before, so I really mean
finding out how to do it. I assume it is easy, but assumption often comes
before a downfall. :-)

Simon.

**Comment by Changaco** [comment]
Indeed it is easy, you just have to click the "Merge pull request" button below.

**Pull request merged**
